<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Data ABK - Export PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
        }
        .header p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 20px;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>LAPORAN DATA ABK</h1>
        <p>Tanggal Export: {{ $generated_at->format('d/m/Y H:i:s') }}</p>
        <p>Total Data: {{ $total_records }} ABK</p>
        @if(isset($exported_by))
            <p>Diekspor oleh: {{ $exported_by }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>NRP</th>
                <th>Nama ABK</th>
                <th>Jabatan Tetap</th>
                <th>Status ABK</th>
                <th>Tanggal Dibuat</th>
            </tr>
        </thead>
        <tbody>
            @foreach($abkData as $index => $abk)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $abk->id }}</td>
                <td>{{ $abk->nama_abk }}</td>
                <td>{{ $abk->jabatanTetap->nama_jabatan ?? '-' }}</td>
                <td>{{ $abk->status_abk }}</td>
                <td>{{ $abk->created_at ? $abk->created_at->format('d/m/Y') : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SertijabPELNI System</p>
    </div>
</body>
</html>